### ISSUE TITLE
Ability to exclude files from directory?

### ISSUE THREAD

**Issue by pkrll** [NSProgrammer/ZipUtilities#10]
Is there a way to exclude certain files (like `.DS_Store` or using wildcards `*.resolve`) from the zipped file when using the NOZCompressRequest method `addEntriesInDirectory:compressionSelectionBlock`?

I haven't figured it out if there is, otherwise, would be possible to add such a feature?

**Comment by NSProgrammer** [comment]
I can see the value of adding that as a feature.  At the moment, you will need to enumerate the directory yourself and add an entry per file you want to compress, filtering out the files you don't want.

I don't foresee myself building that any time soon however, so if you come up with an elegant solution it might be worth creating a pull request.

**Comment by pkrll** [comment]
All right, thanks for the answer!
