### ISSUE TITLE
Add archive integrity testing

### ISSUE THREAD

**Issue by mikemcduffie** [NSProgrammer/ZipUtilities#48]
A feature request to add archive integrity testing analogous to "zip -T".

**Comment by NSProgrammer** [comment]
note to self:
zip -T is a data integrity check.  Simply put, without unzipping an archive to disk, perform the decompression to compute the CRC32 checksum and then check that against the archive's CRC32 (there are 2, so we should check against both and call out what passes/fails)

**Comment by NSProgrammer** [comment]
resolved with new validation method on NOZUnzipper

**Comment by mikemcduffie** [comment]
Cool, thank you!
