### ISSUE TITLE
Commandline tool

### ISSUE THREAD

**Issue by joel-petersen** [NSProgrammer/ZipUtilities#54]
Has someone already written a commandline tool using your library? I think it would be useful to be able to easily produce offline compressed archives that could be used by your library (that could be later used by your library in an ios app).

It would be especially useful for benchmarking given the wide number of compression algorithms you support.

Thanks for the project, it looks really useful.

**Comment by NSProgrammer** [comment]
Not that I know of.  I agree, it would be very useful to add a command line tool for macOS.  I haven't any time, but think that's a great idea.

**Comment by joel-petersen** [comment]
Cool, I'll try to get to it. I'm currently just hacking away at your tests to generate all my zips for benchmarking (where I noticed your runAllCompressionMethodsWithRequest doesnt actually run with all your methods since the zstd/Brotli/LZMA/LZFSE are defined within NOZCoderTests.m and you arent walking them) :-).

Anyway should I make it a branch off your repo with a separate target in your project and do a pull request or just a separate repo/application that includes your library?

**Comment by NSProgrammer** [comment]
Yeah, the test should be updated.  Definitely updating that would be appreciated.

For a command line tool, feel free to put something together in a PR - seems like an appropriate addition to the project.  I'm a stickler though, so don't take it personally if I have a lot of nit picks :)

**Comment by NSProgrammer** [comment]
OK... I've started a CLI tool on a new branch.  Still lots to do, but it's a start: https://github.com/NSProgrammer/ZipUtilities/tree/CLI

@joel-petersen if you have interest in continuing the work on my branch, that would be awesome 😇

**Comment by NSProgrammer** [comment]
Alright... there's now a CLI.  Folks should feel free to modify it and push PRs.  I did not get to implementing Zip Mode, so that is an easy PR for someone.
