### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by matt-curtis** [NSProgrammer/ZipUtilities#55]
Assuming the old adage of "if it doesn't say it's thread-safe, it's not" applies, ZipUtilities is not thread safe... However, I thought I'd ask: is it safe to use separate `NOZUnzipper` instances from different threads?

**Comment by NSProgrammer** [comment]
If you are asking if you can enumerate the records with NOZUnzipper and unzip each record on a different thread, no - that is not possible.  It's really not practically from an I/O access of the file standpoint.

If you are asking if you can have multiple NOZUnzipper instances (each pointing to a separate zip archive file), then YES!   NOZUnzipper is synchronous in execution so it is thread safe within the thread it is called from, but it does not care about what thread it is called from.

Let me know if this answers your question

**Comment by matt-curtis** [comment]
Wow, fast response! Yes, I was asking about the second one, although with the same ZIP file, in an attempt to get some multi-threaded unzipping capability. But it sounds like you're saying that's not possible.

**Comment by NSProgrammer** [comment]
In theory, you could have multiple NOZUnzippers on the same file, yes.  I'd be interested in seeing what results you come up if you can achieve a parallelization boost.

**Comment by matt-curtis** [comment]
Awesome. Thanks for the help.
