### ISSUE TITLE
Error when unzipping the archive

### ISSUE THREAD

**Issue by NSStalker** [NSProgrammer/ZipUtilities#95]
I have the zip file that is successfully unzipped my MacOS 11.4 but ZipUtilities could NOT unzip it.

It unzips several files and then stops and returns a little bit strange error (Error Domain=NSPOSIXErrorDomain Code=21 "Is a directory"). 

The archive is attached.

----
The matter is that I used the library ZipArchive (in my obj-c project) that also has problems with this zip. It turned out that the ZipArchive expects that any file names (inside zip-file) have a UTF8 encoding type. But when I use NSISOLatin2StringEncoding it starts work.

I did not find any references to encoding types in Your library therefore I don't see (at the moment) how to fix this correctly.

[encrypted-update.zip](https://github.com/NSProgrammer/ZipUtilities/files/6667925/encrypted-update.zip)

**Comment by NSProgrammer** [comment]
This is a good find.  ZipUtilities appears to be failing to respect the 11th bit flag, which is the indicator to use either UTF8 string encoding or Windows DOS Latin (Code Page 437) string encoding.

I have a fix locally working, but need to add unit tests.  FWIW, the Mac archive extractor does "succeed" in decoding these archives, however it fails to decode the file names correctly leading to things being broken (in your example, opening "index.html" in Safari will fail to show the 4 navigation icons at the bottom).  My fix will be correct though (in your example, opening "index.html" in Safari will properly display the 4 navigation icons at the bottom).

Thank you for surfacing!

**Comment by NSStalker** [comment]
**_FWIW, the Mac archive extractor does "succeed" in decoding these archives, however, it fails to decode the file names correctly leading to things being broken (in your example, opening "index.html" in Safari will fail to show the 4 navigation icons at the bottom)._**
Thanks a lot! Good to know. I did not notice this because this zip file is one among a long line of possible zip files. Thanks again!

**_My fix will be correct though (in your example, opening "index.html" in Safari will properly display the 4 navigation icons at the bottom)._**
It's perfect news.

**_I have a fix locally working but need to add unit tests._**
Looking forward to it.

**Comment by NSProgrammer** [comment]
@NSStalker OK, it's landed.  I don't have time to update the CocoaPod, but you should now be good to go.

**Comment by NSStalker** [comment]
Thanks!
